version: "3"

volumes:
  mongodb_volume:

services:
  bot_coach:
    build: coach_bot/
    container_name: bot_coach
    restart: always
    environment:
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017
      - RESPONSE_DELAY=120
  mongodb:
    image: mongo:latest
    volumes:
    - mongodb_volume:/data/db
    restart: always